---
title: "my title"
date: 2020-02-11
email: your-email@domain.com
url: "https://coriander345.github.io"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  awesome description
# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  coriander345 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
