---
title: "Coriander-coding blog "
date: 2020-02-11
email: woncha7764@gmail.com
url: "https://coriander345.github.io"
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog. I made this to learn coding, programming and also want to improve my english skill 
  -Get two rabbits at once or Kill two birds with one stone.-
# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  coriander345 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
